[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "2"
path = "2022/2.rs"

[[bin]]
name = "3"
path = "2022/3.rs"
